baseurl = "http://talbright.com/"
title = "talbright"
languageCode = "en-us"
theme = "vec"
paginate = 15

[params]
  Keywords = "developer,aws,go lang,ruby,ruby on rails,cloud,lead"
  Description = "There are some words to describe your site"

  Avater = "img/avatar.png"
  SelfIntro = "Web engineer, open source enthusiast, father, and all around nice guy."
  Email = "trent.albright@gmail.com"

  GithubID = "talbright"
  TwitterID = "trent_albright"
  LinkedInID = "trentalbright"
