languageCode = "en-us"
title = "Aerial"
baseurl = "http://talbright.com/"
theme = "aerial"

[params]
  name = "Trent Albright"
  about = "Lead Platform Engineer @ Salesforce"
  copyright = "Trent Albright"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = "_no_"
  favicon = "favicon.ico"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/trent_albright"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/talbright"

[[params.social]]
  medium = "LinkedIn"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/trentalbright"